### PR TITLE
Make index.py compatible to python3

### LINKED ISSUE #1: Bug in colors.py
The if conditions after [line 16](https://github.com/zscproject/OWASP-ZSC-API/blob/master/core/color.py#L16) are never reached.

### PR DESCRIPTION
**Pull request by CodeMaxx**
@Ali-Razmjoo Can you please check if this is working with python3? I have not yet setup the interface to test the api.
Fixes #1 as well

### CODE REVIEW

**Comment by CodeMaxx** [comment]
@Ali-Razmjoo Ping!

**Comment by Ali-Razmjoo** [comment]
@CodeMaxx  thanks for notification, I wasn't see this, just a question, why did you remove `return ''` in line  16 at color.py ?

**Comment by CodeMaxx** [comment]
I have not removed that line

**Comment by Ali-Razmjoo** [comment]
thanks, merged.

**Pull request merged**
